import AboutSection from "@/components/Sections/About";
import InitSection from "@/components/Sections/Init";
// import WorkSection from "@/components/Sections/Works";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: "grid", gap: "5rem" }}>
        <InitSection />
        <AboutSection />
        {/* <WorkSection /> */}
      </main>
    </>
  );
}
